# Task-1

In [92]:
import numpy as np
rng =np.random.default_rng(seed=0)
readings=rng.normal(50,25,size=(360,4))

In [93]:
readings

array([[ 53.14325553,  46.69737842,  66.01056626,  52.62250293],
       [ 36.60826567,  59.03987637,  82.60000113,  73.67702408],
       [ 32.4066191 ,  18.36446322,  34.41813844,  51.03314948],
       ...,
       [ 34.15349506,  57.40947596,  43.5602629 ,  15.82067965],
       [ 49.34608034,  89.89256102, 100.06330794,  35.82396349],
       [ 72.63186509,  53.31323637,  57.09716574,  81.68428033]],
      shape=(360, 4))

In [94]:
readings.dtype

dtype('float64')

In [95]:
readings.shape

(360, 4)

In [96]:
readings[:3]

array([[53.14325553, 46.69737842, 66.01056626, 52.62250293],
       [36.60826567, 59.03987637, 82.60000113, 73.67702408],
       [32.4066191 , 18.36446322, 34.41813844, 51.03314948]])

# Task-2

In [97]:
scaled_readings=(readings-readings.min())/(readings.max()-readings.min())
scaled_readings

array([[0.57787323, 0.54085699, 0.65176534, 0.57488274],
       [0.48291902, 0.61173529, 0.7470322 , 0.69579091],
       [0.45879055, 0.37815174, 0.47034194, 0.56575568],
       ...,
       [0.4688222 , 0.60237252, 0.52284171, 0.36354375],
       [0.55606748, 0.78891062, 0.84731738, 0.47841507],
       [0.68978896, 0.57884936, 0.60057904, 0.74177356]], shape=(360, 4))

In [98]:
scaled_readings.min()

np.float64(0.0)

In [99]:
scaled_readings.max()

np.float64(1.0)

In [100]:
column_means=readings.mean(axis=0)
centered_readings=readings-column_means

In [101]:
centered_readings

array([[  3.55431931,  -1.55693686,  17.57807183,   0.11034473],
       [-12.98067055,  10.7855611 ,  34.1675067 ,  21.16486588],
       [-17.18231711, -29.88985205, -14.01435599,  -1.47900871],
       ...,
       [-15.43544116,   9.15516068,  -4.87223153, -36.69147855],
       [ -0.24285588,  41.63824574,  51.63081351, -16.68819471],
       [ 23.04292887,   5.05892109,   8.66467131,  29.17212213]],
      shape=(360, 4))

In [102]:
print(scaled_readings.shape==readings.shape)
print(centered_readings.shape==readings.shape)

True
True


# Task-3

In [103]:
rng =np.random.default_rng(seed=0)
readings=rng.normal(50,10,size=(360,4))

In [104]:
outlier_mask=(readings<20)|(readings>80)

In [105]:
outlier_count=np.sum(outlier_mask)
outlier_count

np.int64(5)

In [106]:
total_count=readings.size
total_count

1440

In [107]:
outlier_percent=(outlier_count/total_count)*100
outlier_percent

np.float64(0.3472222222222222)

In [108]:
cleaned_readings=readings.copy()

In [109]:
cleaned_readings[outlier_mask]=np.nan
cleaned_readings

array([[51.25730221, 48.67895137, 56.4042265 , 51.04900117],
       [44.64330627, 53.61595055, 63.04000045, 59.47080963],
       [42.96264764, 37.34578529, 43.76725537, 50.41325979],
       ...,
       [43.66139802, 52.96379038, 47.42410516, 36.32827186],
       [49.73843213, 65.95702441, 70.02532317, 44.3295854 ],
       [59.05274604, 51.32529455, 52.8388663 , 62.67371213]],
      shape=(360, 4))

In [110]:
nan_count=np.sum(np.isnan(cleaned_readings))
nan_count

np.int64(5)

In [111]:
print(nan_count==outlier_count)

True


# Task-4

In [112]:
sensor_means=readings.mean(axis=0)
sensor_stds=readings.std(axis=0)

In [113]:
sensor_means

array([49.83557449, 49.30172611, 49.37299777, 51.00486328])

In [114]:
sensor_stds

array([ 9.74752295,  9.59309985,  9.99833748, 10.18720053])

In [115]:
time_means=readings.mean(axis=1)
time_means

array([51.84737031, 55.19251673, 43.62223702, 38.69499815, 51.48396192,
       52.31061051, 48.33064463, 46.35918885, 52.37913102, 53.73491093,
       55.95511267, 58.42202954, 55.66450103, 49.3969535 , 48.2002147 ,
       49.09304998, 57.43557737, 47.91389477, 52.21908731, 55.81242291,
       45.2165387 , 53.07113989, 55.55380558, 50.28242329, 42.08185206,
       50.63434108, 48.75149492, 44.15966821, 50.15553764, 60.38918114,
       50.70121666, 44.82787821, 44.06765527, 56.77263627, 53.53952569,
       53.79343985, 44.87487721, 50.17785104, 42.85715833, 41.52665048,
       48.62326263, 50.91555341, 59.19858662, 54.37149436, 43.45017523,
       47.91352701, 52.48843585, 41.56275979, 55.99088318, 45.6136064 ,
       44.6181174 , 48.00114108, 58.38058005, 50.40850923, 54.07502626,
       44.83858342, 54.27624352, 40.87468358, 50.89319008, 32.54754539,
       53.2921451 , 60.32576753, 46.54344939, 54.50539008, 52.52653208,
       43.57706674, 49.91413126, 53.88289789, 42.20976257, 48.56

In [116]:
print(sensor_means.shape==(4,))
print(sensor_stds.shape==(4,))
print(time_means.shape==(360,))

True
True
True


# Task-5

In [117]:
report = {
    "total_readings": total_count,
    "outlier_count": outlier_count,
    "outlier_percent": outlier_percent,
    "sensor_means": sensor_means,
    "sensor_stds": sensor_stds
}
report_str = f"""
Report Summary

Total readings    : {report['total_readings']}
Outlier count     : {report['outlier_count']}
Outlier percent   : {report['outlier_percent']:.2f}%
Sensor means      : {report['sensor_means']}
Sensor stds       : {report['sensor_stds']}
"""

print(report_str)



Report Summary

Total readings    : 1440
Outlier count     : 5
Outlier percent   : 0.35%
Sensor means      : [49.83557449 49.30172611 49.37299777 51.00486328]
Sensor stds       : [ 9.74752295  9.59309985  9.99833748 10.18720053]



# Task-6

In [118]:
import numpy as np
rng = np.random.default_rng(seed=0)
sim = rng.normal(0, 1, size=(1000, 6))

In [119]:
sim

array([[ 0.12573022, -0.13210486,  0.64042265,  0.10490012, -0.53566937,
         0.36159505],
       [ 1.30400005,  0.94708096, -0.70373524, -1.26542147, -0.62327446,
         0.04132598],
       [-2.32503077, -0.21879166, -1.24591095, -0.73226735, -0.54425898,
        -0.31630016],
       ...,
       [ 0.94943846,  1.02922814,  0.31886802,  1.05773509,  0.26838522,
         0.35055328],
       [-0.12294856,  2.00252255,  1.63391972, -0.49129481,  0.87095129,
         0.24026025],
       [-0.22681171,  0.74016406,  0.18054669,  0.15984538, -0.2263336 ,
        -0.09355873]], shape=(1000, 6))

In [120]:
sim.shape

(1000, 6)

In [121]:
sim.dtype

dtype('float64')

In [122]:
sim[:3]

array([[ 0.12573022, -0.13210486,  0.64042265,  0.10490012, -0.53566937,
         0.36159505],
       [ 1.30400005,  0.94708096, -0.70373524, -1.26542147, -0.62327446,
         0.04132598],
       [-2.32503077, -0.21879166, -1.24591095, -0.73226735, -0.54425898,
        -0.31630016]])

# Task-7

In [123]:
scenario_shift=np.array([-0.3, -0.1, 0.0, 0.1, 0.2, 0.4])
adjusted_sim=sim+scenario_shift

In [124]:
adjusted_sim

array([[-0.17426978, -0.23210486,  0.64042265,  0.20490012, -0.33566937,
         0.76159505],
       [ 1.00400005,  0.84708096, -0.70373524, -1.16542147, -0.42327446,
         0.44132598],
       [-2.62503077, -0.31879166, -1.24591095, -0.63226735, -0.34425898,
         0.08369984],
       ...,
       [ 0.64943846,  0.92922814,  0.31886802,  1.15773509,  0.46838522,
         0.75055328],
       [-0.42294856,  1.90252255,  1.63391972, -0.39129481,  1.07095129,
         0.64026025],
       [-0.52681171,  0.64016406,  0.18054669,  0.25984538, -0.0263336 ,
         0.30644127]], shape=(1000, 6))

In [125]:
adjusted_sim.size==sim.size

True

In [126]:
sim_mean=sim.mean(axis=0)

In [127]:
adjusted_mean=adjusted_sim.mean(axis=0)

In [128]:
(adjusted_mean-sim_mean)==scenario_shift

array([False, False,  True, False, False, False])

# Task-8

In [129]:
scenario_means=adjusted_sim.mean(axis=0)

In [130]:
scenario_means

array([-0.33621381, -0.04969297,  0.01921678,  0.0638128 ,  0.19477725,
        0.39966337])

In [131]:
ordered_scenarios=np.argsort(scenario_means)

In [132]:
ordered_scenarios

array([0, 1, 2, 3, 4, 5])

In [133]:
partitioned=np.partition(scenario_means,-2)

In [134]:
partitioned

array([-0.04969297, -0.33621381,  0.01921678,  0.0638128 ,  0.19477725,
        0.39966337])

In [135]:
sorted=np.sort(scenario_means)

In [136]:
sorted[-2:]==partitioned[-2:]

array([ True,  True])

# Task-9

In [137]:
rng2 = np.random.default_rng(seed=0)
sim_2 = rng2.normal(0, 1, size=(1000, 6))


In [138]:
print(np.allclose(sim, sim_2))

True


In [139]:
rng3=np.random.default_rng(seed=3)
sim_3=rng3.normal(0,1,size=(1000,6))

In [140]:
print(np.allclose(sim, sim_3))

False


# Task-10

In [141]:

scenario_means = adjusted_sim.mean(axis=0)
top_two_indices = np.argsort(scenario_means)[-2:]
top_two_values = scenario_means[top_two_indices]



In [142]:
print(len(scenario_means) == 6)

True


In [143]:
print(len(top_two_indices) == 2)

True


In [144]:
report = {
    "shape": adjusted_sim.shape,
    "scenario_means": scenario_means,
    "top_two_indices": top_two_indices,
    "top_two_values": top_two_values
}

In [145]:
report=f"""
Simulation Report
Shape: {report['shape']}
Scenario means: {report['scenario_means']}
Top two indices: {report['top_two_indices']}
Top two values: {report['top_two_values']}
"""

In [146]:
print(report)


Simulation Report
Shape: (1000, 6)
Scenario means: [-0.33621381 -0.04969297  0.01921678  0.0638128   0.19477725  0.39966337]
Top two indices: [4 5]
Top two values: [0.19477725 0.39966337]

